events {}

http {
  upstream fanzoom_web {
    server web1:3000;
    server web2:3000;
    server web3:3000;
  }

  server {
    listen 8080;
    location / {
      proxy_pass http://fanzoom_web;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto http;
      proxy_set_header X-Request-Id $http_x_request_id;
      add_header X-Fanzoom-Test-Upstream $upstream_addr always;
    }
  }
}
